name: Build pipeline
on:
  push:
    branches: [main]
  pull_request:

permissions: {}

env:
  RUST_TOOLCHAIN_VERSION: "1.94.0"
  RUSTFLAGS: "-D warnings"
  RUSTDOCFLAGS: "-D warnings"
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - run: rustup toolchain install "${RUST_TOOLCHAIN_VERSION}"
      - run: cargo test --all-features

  clippy:
    name: Check clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - run: rustup toolchain install "${RUST_TOOLCHAIN_VERSION}" --component clippy
      - run: cargo clippy --all-targets -- -D warnings

  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - run: rustup toolchain install "${RUST_TOOLCHAIN_VERSION}" --component rustfmt
      - run: cargo fmt --all -- --check

  docs:
    name: Generate docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - run: rustup toolchain install "${RUST_TOOLCHAIN_VERSION}"
      - run: cargo doc --document-private-items

  build:
    name: Build and push container image
    needs: [test, clippy, fmt, docs]
    permissions:
      id-token: write
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - ubicloud-standard-8-arm
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Build and (optionally) push container image
        id: build
        uses: stackabletech/actions/build-container-image@a14cbd08d9e034e2361ea9205b32aff0491885db # v0.15.0
        with:
          image-name: trino-lb
          image-index-manifest-tag: dev
          container-file: docker/Dockerfile

      - name: Publish Container Image on oci.stackable.tech
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: stackabletech/actions/publish-image@a14cbd08d9e034e2361ea9205b32aff0491885db # v0.15.0
        with:
          image-registry-uri: oci.stackable.tech
          image-registry-username: robot$stackable+github-action-build
          image-registry-password: ${{ secrets.HARBOR_ROBOT_STACKABLE_GITHUB_ACTION_BUILD_SECRET }}
          # trino-lb is not (yet) a product as the SDP, but a community project, so use "stackable" instead of "sdp"
          image-repository: stackable/trino-lb
          image-manifest-tag: ${{ steps.build.outputs.image-manifest-tag }}
          source-image-uri: ${{ steps.build.outputs.image-manifest-uri }}

  publish_manifests:
    name: Build and publish index manifest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [build]
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Publish and Sign Image Index Manifest to oci.stackable.tech
        uses: stackabletech/actions/publish-image-index-manifest@a14cbd08d9e034e2361ea9205b32aff0491885db # v0.15.0
        with:
          image-registry-uri: oci.stackable.tech
          image-registry-username: robot$stackable+github-action-build
          image-registry-password: ${{ secrets.HARBOR_ROBOT_STACKABLE_GITHUB_ACTION_BUILD_SECRET }}
          # trino-lb is not (yet) a product as the SDP, but a community project, so use "stackable" instead of "sdp"
          image-repository: stackable/trino-lb
          image-index-manifest-tag: dev
